# Generated by Django 4.2 on 2024-10-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Tax Rates'},
        ),
    ]
